repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.2.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
    -   repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
        rev: v1.1.1
        hooks:
        -   id: htmlhint
        -   id: htmllint
    - repo: https://github.com/codespell-project/codespell
      rev: v1.17.1
      hooks:
        - id: codespell
          files: \.(md|rst)$
